//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Editor.rc
//
#define IDCPREVIEW                      3
#define IDDETAILS                       3
#define IDPREVOBJECT                    3
#define IDLOGIN                         4
#define IDNEXTOBJECT                    4
#define IDBUY                           5
#define IDADDTOCART                     5
#define IDR_EDITORTYPE_CNTR_IP          6
#define IDSEARCH                        6
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_MAIN_TOOLBAR                101
#define IDP_FAILED_TO_CREATE            102
#define IDS_WINDOWS_MANAGER             107
#define IDB_SPLASH                      108
#define IDD_OBJECTDETAILSDIALOG         109
#define IDD_LOGINDIALOG                 110
#define IDD_HELPWIZARD                  111
#define IDD_TAB2                        112
#define IDD_TAB3                        113
#define IDD_AUTOUPDATE                  114
#define IDD_SEARCHDIALOG                115
#define IDD_MARKET                      116
#define IDD_UPLOADAPP_DIALOG            117
#define IDD_ARTMSGDIALOG                118
#define IDD_EDITDIALOG                  119
#define IDD_DISPLAYFILTERS              120
#define IDR_MAINFRAME                   128
#define IDR_EDITORTYPE                  129
#define IDR_CONTEXT_MENU                130
#define IDR_POPUP_TOOLBAR               131
#define XX_IDR_EDITORTYPE_CNTR_IP       132
#define IDB_WORKSPACE                   147
#define IDB_TOOLBAR256                  151
#define IDB_TOOLBARCOLD256              152
#define IDR_VIEW                        155
#define IDR_MODE                        157
#define IDR_PROPERTY                    159
#define IDR_DRAW                        161
#define IDR_SELECTION                   163
#define IDR_SEGMENT                     165
#define IDR_ENTITY                      167
#define IDR_WAYPOINT                    169
#define IDD_BROWSER                     171
#define IDD_NEWPROJECT                  172
#define IDD_LEVELRESIZE                 173
#define IDD_PREFERENCES                 174
#define IDD_BROWSER_NEW                 175
#define IDB_BITMAP1                     176
#define IDB_BITMAP2                     177
#define IDB_BITMAP3                     178
#define IDB_BITMAP4                     179
#define IDB_BITMAP5                     180
#define IDB_BITMAP6                     181
#define IDB_BITMAP7                     182
#define IDR_GAME                        183
#define IDB_BITMAP8                     186
#define IDB_BITMAP9                     187
#define IDD_LIBRARY                     187
#define IDD_NEW_LIBRARY                 188
#define IDD_BUILD_GAME                  190
#define IDD_BUILD_GAME_PROJECT          191
#define IDD_BUILD_GAME_LEVEL            192
#define IDD_BUILD_GAME_BUILD            193
#define IDD_TEST_GAME                   194
#define IDD_BUILD_GAME_LIGHT            195
#define IDD_BUILD_GAME_KEYS             197
#define IDB_BITMAP10                    198
#define IDD_BUILD_GAME_WEAPONS          198
#define IDB_BITMAP11                    200
#define IDD_DIALOG_FPI                  201
#define IDB_BITMAP12                    202
#define IDB_BITMAP13                    203
#define IDD_FRONT                       204
#define IDD_POPUP                       205
#define IDB_WORKSPACE_DIS               206
#define IDB_BITMAP14                    207
#define IDB_ADD_MAIN_FRAME              208
#define IDB_ADD_MAIN_FRAME_DIS          209
#define IDD_DIALOG1                     210
#define IDD_CREDITS                     211
#define IDD_DIALOG_FRONT                212
#define IDD_DIALOG_END                  213
#define IDD_BUILD_GAME_MULTIPLAYER      214
#define IDB_IMAGE                       216
#define IDB_STAR                        218
#define IDB_EMPTY_STAR                  219
#define IDD_DIALOG2                     220
#define IDB_HELP_INTRO                  222
#define IDB_SAMPLE_IMAGE                223
#define IDB_UPDATE_LOGO                 225
#define IDB_MASK_STAR                   227
#define IDB_STORE_ICON                  229
#define IDB_BITMAP15                    232
#define IDB_FOLDER_ICON                 232
#define IDB_SEARCH_RESULTS              233
#define IDB_SHOPPING_CART               234
#define IDB_ONLINE_ITEMS                235
#define IDR_CART_MENU                   236
#define IDR_CART_ADD_MENU               237
#define IDR_MENU1                       238
#define IDR_ADMIN_ADD_MENU              238
#define IDR_ADMIN_DELETE_MENU           240
#define IDR_ADMIN_NORMAL_MENU           241
#define IDB_IN_CART                     242
#define IDB_BITMAP16                    244
#define IDB_NO_THUMBNAIL                244
#define IDB_STORE_BUTTON                245
#define IDB_BITMAP17                    246
#define IDB_MUSIC_PREVIEW               246
#define IDB_BITMAP18                    247
#define IDC_COMBO_TITLE_SCREEN          1006
#define IDC_COMBO_WEAPONS               1006
#define IDC_COMBO_GAME_MENU             1007
#define IDC_COMBO_GAME_OVER             1008
#define IDC_COMBO_GAME_COMPLETE         1009
#define IDC_COMBO_GAME_HOST             1010
#define IDC_SPLIT_MID                   1011
#define IDC_UPLOAD_TEXT                 1021
#define IDC_COMBO3                      1022
#define IDC_PROGRESS_SPINNER            1023
#define IDC_COMBO4                      1024
#define IDC_NEW_GROUP_TEXT              1025
#define IDC_EDIT8                       1026
#define IDC_COMPANY_URL                 1041
#define IDC_EDIT1                       1042
#define IDC_COMPANY_URL2                1042
#define IDC_EDIT2                       1043
#define IDC_EDIT3                       1044
#define IDC_EDIT4                       1045
#define IDC_EDIT_NEW                    1045
#define IDC_EDIT5                       1046
#define IDC_TAB1                        1047
#define IDC_EDIT6                       1047
#define IDC_LIST1                       1048
#define IDC_EDIT7                       1048
#define IDC_TREE1                       1049
#define IDC_LIST3                       1049
#define IDC_LIST_MAP_NAMES              1049
#define IDC_EDIT10                      1049
#define IDC_LIST2                       1050
#define IDC_LIST4                       1050
#define IDC_LIST_MAP_LEVEL_LOAD         1050
#define IDC_EDIT9                       1050
#define IDC_LIST5                       1051
#define IDC_LIST_MAP_SETUPANDGOALS      1051
#define IDC_LIST_MAP_LOADING_SCREEN     1051
#define IDC_BUTTON1                     1052
#define IDC_BUTTON_EXECUTABLE_PATH      1052
#define IDC_LIST6                       1052
#define IDC_IMAGE_RIGHT                 1052
#define IDC_BUTTON2                     1053
#define IDC_BUILD_GAME_BUTTON_OK        1053
#define IDC_IMAGE_LEFT                  1053
#define IDC_BUTTON3                     1054
#define IDC_BUILD_GAME_BUTTON_CANCEL    1054
#define IDC_BUTTON6                     1055
#define IDC_RADIO1                      1055
#define IDC_BUILD_GAME_BUTTON_HELP      1055
#define IDC_LOW                         1055
#define IDC_PAGE_RIGHT                  1055
#define IDC_BUTTON4                     1056
#define IDC_RADIO2                      1056
#define IDC_BUTTON_PREVIEW_LEVEL        1056
#define IDC_MEDIUM                      1056
#define IDC_BUTTON5                     1057
#define IDC_RADIO3                      1057
#define IDC_BUTTON_DELETE_LEVEL         1057
#define IDC_HIGH                        1057
#define IDC_BUTTON7                     1058
#define IDC_RADIO4                      1058
#define IDC_BUTTON_GAME_COMPLETE_STYLE  1058
#define IDC_RADIO_NO_EFFECTS            1058
#define IDC_BUTTON_GAME_COMPLETE        1058
#define IDC_QUICK_LIGHT_MAPPING         1058
#define IDC_PAGE_LEFT                   1058
#define IDC_BUTTON8                     1059
#define IDC_RADIO5                      1059
#define IDC_BUTTON_GAME_HOST_STYLE      1059
#define IDC_RADIO_ESSENTIAL_EFFECTS     1059
#define IDC_FULL_LIGHT_MAPPING          1059
#define IDC_PAGE_FIRST                  1059
#define IDC_RADIO6                      1060
#define IDC_BUTTON_GAME_OVER_PREVIEW    1060
#define IDC_RADIO_FULL_EFFECTS          1060
#define IDC_BUTTON_NEW_LEVEL_SCRIPT     1060
#define IDC_NO_EFFECTS                  1060
#define IDC_PAGE_LAST                   1060
#define IDC_BUTTON11                    1060
#define IDC_RADIO7                      1061
#define IDC_BUTTON_GAME_COMPLETE_PREVIEW 1061
#define IDC_RADIO_SINGLE                1061
#define IDC_ESSENTIAL_EFFECTS           1061
#define IDC_RADIO8                      1062
#define IDC_BUTTON_GAME_HOST_PREVIEW    1062
#define IDC_RADIO_DEATHMATCH            1062
#define IDC_FULL_EFFECTS                1062
#define IDC_PREVIEW_LIST                1063
#define IDC_RADIO9                      1063
#define IDC_BUTTON_TITLE_SCREEN_STYLE   1063
#define IDC_RADIO_COOP                  1063
#define IDC_BUTTON_TITLE_SCREEN         1063
#define IDC_NO_LIGHT_MAPPING            1063
#define IDC_IPADDRESS1                  1064
#define IDC_BUTTON_GAME_MENU_STYLE      1064
#define IDC_BUTTON_GLOBAL_SCRIPT        1064
#define IDC_SINGLE_PLAYER               1064
#define IDC_PROGRESS1                   1065
#define IDC_PROGRESS_PROJECT            1065
#define IDC_PROGRESS_FRONT_1            1065
#define IDC_MULTIPLAYER                 1065
#define IDC_STATUS_PROGRESS             1065
#define IDC_STATIC_1                    1068
#define IDC_BUTTON_PROJECT_FILENAME     1069
#define IDC_STATIC_10                   1069
#define IDC_LIST_COMMANDS               1070
#define IDC_BUTTON_PROJECT_NEW          1070
#define IDC_STATIC_11                   1070
#define IDC_EDIT_PROJECT_FILENAME       1071
#define IDC_STATIC_12                   1071
#define IDC_LIST_KEY                    1072
#define IDC_EDIT_INFO                   1073
#define IDC_EDIT_TEXT                   1074
#define IDC_EDIT_INFO2                  1074
#define IDC_EDIT_INFO_2                 1074
#define IDC_CHECK1                      1075
#define IDC_DYNAMIC_LIGHTING            1075
#define IDC_MP_OBJECTIVE                1075
#define IDC_CHECK2                      1076
#define IDC_EDIT_INFORMATION            1076
#define IDC_DYNAMIC_SHADOWS             1076
#define IDC_MP_FIRSTTO                  1076
#define IDC_CHECK3                      1077
#define IDC_PROGRESS                    1077
#define IDC_MP_HIGHESTFRAG              1077
#define IDC_CHECK4                      1078
#define IDC_EDIT_STATUS                 1078
#define IDC_EDIT_TITLE_SCREEN           1078
#define IDC_MP_ONESHOT                  1078
#define IDC_CHECK5                      1079
#define IDC_EDIT_GAME_MENU              1079
#define IDC_MP_DEFAULT                  1079
#define IDC_CHECK6                      1080
#define IDC_BUTTON_TITLE_SCREEN_PREVIEW 1080
#define IDC_MP_RANDOM                   1080
#define IDC_CHECK7                      1081
#define IDC_BUTTON_GAME_MENU_PREVIEW    1081
#define IDC_LIST_MAP_NUMBERS            1082
#define IDC_HSR                         1082
#define IDC_BUTTON_ADD_LEVEL            1083
#define IDC_LIST_KEY1                   1083
#define IDC_BUTTON_INSERT_LEVEL         1083
#define IDC_SHOW_ENTITY                 1083
#define IDC_EDIT_GAME_OVER              1084
#define IDC_LIST_TITLE_SCREEN           1084
#define IDC_LIST_WEAPONS_TYPE           1084
#define IDC_SHOW_DEBUG                  1084
#define IDC_BUTTON_GAME_OVER_STYLE      1085
#define IDC_BUTTON_GAME_OVER            1085
#define IDC_NO_FLOOR                    1085
#define IDC_EDIT_GAME_COMPLETE          1086
#define IDC_LIST_GLOBAL_SCRIPT          1086
#define IDC_EDIT_GAME_HOST              1087
#define IDC_LIST_GAME_OVER              1087
#define IDC_PURCHASE_PASS               1087
#define IDC_LIST_GAME_COMPLETE          1088
#define IDC_AUTO_LOGIN                  1088
#define IDC_BUTTON_ADD_LEVEL2           1089
#define IDC_EDIT_PROJECT_STATUS         1090
#define IDC_BUTTON_BUILD                1091
#define IDC_OK                          1092
#define IDC_WEAPON_OK                   1092
#define IDC_EDIT_KEYS                   1093
#define IDC_EDIT_INFO_1                 1094
#define IDC_EDIT_PATH                   1095
#define IDC_LIST_COMMANDS1              1096
#define IDC_EDIT_PATH2                  1096
#define IDC_RADIO_NO_LIGHTMAPS          1097
#define IDC_LIST_WEAPONS_NUMBER         1097
#define IDC_RADIO_SOFT_LIGHTMAPS        1098
#define IDC_RADIO_FULL_SHADOW_LIGHTMAPS 1099
#define IDC_RADIO_LOW                   1100
#define IDC_STATIC_2                    1101
#define IDC_STATIC_3                    1102
#define IDC_RADIO_MEDIUM                1103
#define IDC_STATIC_WEAPON_INFO          1103
#define IDC_STATIC_WEAPON_2             1103
#define IDC_RADIO_HIGH                  1104
#define IDC_CHECK_HSR                   1105
#define IDC_STATIC_4                    1105
#define IDC_CHECK_DYNAMIC_SHADOWS       1106
#define IDC_CHECK_DYNAMIC_LIGHTS        1107
#define IDC_STATIC_VERSION              1110
#define IDC_STATIC_CREDITS_1            1110
#define IDC_STATIC_POPUP                1111
#define IDC_STATIC_VERSION2             1111
#define IDC_STATIC_CREDITS_2            1111
#define IDC_STATIC_VERSION3             1112
#define IDC_STATIC_CREDITS_3            1112
#define IDC_STATIC_VERSION4             1113
#define IDC_STATIC_CREDITS_4            1113
#define IDC_STATIC_VERSION5             1114
#define IDC_STATIC_CREDITS_5            1114
#define IDC_STATIC_VERSION6             1115
#define IDC_STATIC_CREDITS_6            1115
#define IDC_STATIC_VERSION7             1116
#define IDC_STATIC_CREDITS_7            1116
#define IDC_STATIC_VERSION8             1117
#define IDC_STATIC_CREDITS_8            1117
#define IDC_STATIC_VERSION9             1118
#define IDC_STATIC_CREDITS_9            1118
#define IDC_STATIC_VERSION10            1119
#define IDC_STATIC_CREDITS_10           1119
#define IDC_STATIC_VERSION11            1120
#define IDC_STATIC_VERSION12            1121
#define IDC_STATIC_FRONT_TEXT           1121
#define IDC_STATIC_VERSION13            1122
#define IDC_STATIC_FRONT1               1122
#define IDC_STATIC_VERSION14            1123
#define IDC_STATIC_VERSION15            1124
#define IDC_ABOUT_LINE1                 1124
#define IDC_STATIC_VERSION16            1125
#define IDC_ABOUT_LINE2                 1125
#define IDC_STATIC_VERSION17            1126
#define IDC_ABOUT_LINE3                 1126
#define IDC_STATIC_VERSION18            1127
#define IDC_ABOUT_LINE4                 1127
#define IDC_STATIC_VERSION19            1128
#define IDC_ABOUT_LINE5                 1128
#define IDC_STATIC_VERSION20            1129
#define IDC_STATIC_CREDITS_11           1129
#define IDC_TEST_BOX1                   1129
#define IDC_STATIC_VERSION21            1130
#define IDC_TEST_BOX2                   1130
#define IDC_TEST_BOX3                   1131
#define IDC_STATIC_VERSION22            1131
#define IDC_TEST_BOX4                   1132
#define IDC_STATIC_VERSION23            1132
#define IDC_TEST_BOX5                   1133
#define IDC_STATIC_VERSION24            1133
#define IDC_STATIC_5                    1134
#define IDC_TEST_BOX6                   1134
#define IDC_STATIC_6                    1135
#define IDC_TEST_BOX7                   1135
#define IDC_STATIC_7                    1136
#define IDC_STATIC_8                    1137
#define IDC_STATIC_9                    1138
#define IDC_STATIC_KEY_SELECT           1139
#define IDC_STATIC_WEAPON_1             1140
#define IDC_STATIC_NEW_PROJECT_1        1141
#define IDC_MP_EDIT1                    1142
#define IDC_MP_EDIT2                    1143
#define IDC_MP_EDIT3                    1144
#define IDC_STATIC_FRAGS                1145
#define IDC_STATIC_SECONDS              1146
#define IDC_STATIC_NUMPLR               1147
#define IDC_STATIC_HOW                  1148
#define IDC_CUSTOM1                     1149
#define IDC_USERNAME                    1150
#define IDC_PASSWORD                    1151
#define IDC_OBJECT_NAME                 1152
#define IDC_OBJECT_COST                 1153
#define IDC_OBJECT_RATING               1155
#define IDC_IMAGE_COUNTER               1157
#define IDC_LOADING                     1158
#define IDC_CREDITS                     1159
#define IDC_CREDITSTEXT                 1160
#define IDC_LOGGEDINTEXT                1161
#define IDC_IMAGES                      1162
#define IDC_DESCRIPTION_BOX             1163
#define IDC_STATUS_TEXT                 1164
#define IDC_STATIC_LABEL                1165
#define IDC_INTRO_IMAGE                 1166
#define IDC_BLACK_BOX                   1167
#define IDC_AUPDATE_TEXT                1168
#define IDC_UPDATE_IMAGE                1169
#define IDC_CURR_VERSION                1170
#define IDC_LATEST_VERSION              1171
#define IDC_NAME                        1172
#define IDC_COST                        1173
#define IDC_CATEGORY                    1174
#define IDC_AUTHOR                      1175
#define IDC_RATING                      1176
#define IDC_THUMBNAIL                   1177
#define IDC_TEXT_REDOWNLOAD             1178
#define IDC_TEXT_NAME                   1179
#define IDC_TEXT_CATEGORY               1180
#define IDC_TEXT_COST                   1181
#define IDC_POLYGONS                    1182
#define IDC_TEXT_AUTHOR                 1183
#define IDC_TEXT_RATING                 1184
#define IDC_TEXT_DESCRIPTION            1185
#define IDC_COMBO1                      1185
#define IDC_TEXT_ORDER_BY               1186
#define IDC_TEXT_POLYGONS               1186
#define IDC_TYPE_NAME                   1187
#define IDC_COMBO2                      1188
#define IDC_TEXT_RATE                   1189
#define IDC_TYPE                        1190
#define IDC_TEXT_NO_ITEMS               1191
#define IDC_TEXT_FILESIZE               1191
#define IDC_EXPLORER1                   1192
#define IDC_FILESIZE                    1192
#define IDC_TEXT_USERNAME               1193
#define IDC_TEXT_DOWNLOADS              1193
#define IDC_TEXT_PASSWORD               1194
#define IDC_DOWNLOADS                   1194
#define IDC_LOGIN_USERNAME              1195
#define IDC_VIDEO_LINK                  1195
#define IDC_LOGIN_PASSWORD              1196
#define IDC_LOGIN_REGISTER              1197
#define IDC_LOGIN_STATEMENT             1198
#define IDC_SEARCH_STATEMENT            1199
#define IDC_LOGIN_STATEMENT2            1199
#define IDC_SEARCH_NAME                 1200
#define IDC_SEARCH_CATEGORY             1201
#define IDC_SEARCH_COST1                1202
#define IDC_SEARCH_COST2                1203
#define IDC_SEARCH_AUTHOR               1204
#define IDC_SEARCH_RATING1              1205
#define IDC_SEARCH_RATING2              1206
#define IDC_SEARCH_KEYWORD              1207
#define IDC_EDIT_DESCRIPTION            1208
#define IDC_STORE_MAIN_BUTTON           1209
#define IDC_STORE_BUTTON                1210
#define IDC_EXPLORER2                   1210
#define IDC_AD_BUTTON                   1211
#define IDC_BUTTON9                     1212
#define IDC_BOX1                        1213
#define IDC_BOX2                        1214
#define IDC_BOX3                        1215
#define IDC_BOX4                        1216
#define IDC_MSG                         1220
#define IDC_CART_TOTAL                  1221
#define IDC_CART_TOTAL_LABEL            1222
#define IDC_STORE_BORDER                1223
#define IDC_SAMPLE_IMAGE                1224
#define IDC_BUTTON10                    1225
#define IDC_PAGE_COUNTER                1226
#define IDC_GIF_BOX                     1227
#define IDC_ITEMS_PER_PAGE              1228
#define IDC_PAGE_COMBO                  1229
#define IDC_APPROVAL_ITEMS              1230
#define IDC_MODEL_DESC                  1231
#define IDC_MODEL_LABEL                 1232
#define IDC_PREVIEW_DESC                1233
#define IDC_PREVIEW_LABEL               1234
#define IDC_ADD                         1235
#define IDC_REMOVE                      1236
#define IDC_NAME_LABEL                  1237
#define IDC_COMPATIBLE_LABEL            1238
#define IDC_SUBCATEGORY                 1239
#define IDC_KEYWORDS                    1240
#define IDC_DESCRIPTION                 1241
#define IDC_THUMBNAIL_LABEL             1242
#define IDC_TEXT_SEARCH                 1243
#define IDC_MODEL_LABEL2                1243
#define IDC_PROGRESS_SEARCH             1244
#define IDC_MODEL_FILE                  1245
#define IDC_THUMB_LABEL                 1246
#define IDC_LABEL_PREVIEW               1247
#define IDC_THUMB_IMAGE_LABEL           1248
#define IDC_PREVIEW_IMAGE_LABEL         1249
#define IDC_LABEL_NAME                  1250
#define IDC_LABEL_COMPAT                1251
#define IDC_LABEL_COST                  1252
#define IDC_LABEL_POLYGONS              1253
#define IDC_LABEL_KEYWORDS              1254
#define IDC_LABEL_DESC                  1255
#define IDC_THUMB_LABEL2                1256
#define IDC_MEDIA_PROGRESS              1256
#define IDC_MEDIA_TEXT                  1257
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_VIEW_CUSTOMIZE               32770
#define ID_VIEW_TOOLBARS                32771
#define ID_VIEW_WORKSPACE               32803
#define ID_VIEW_OUTPUT                  32804
#define ID_TOOLS_ENTRY                  32805
#define ID_USER_TOOL1                   32806
#define ID_USER_TOOL2                   32807
#define ID_USER_TOOL3                   32808
#define ID_USER_TOOL4                   32809
#define ID_USER_TOOL5                   32810
#define ID_USER_TOOL6                   32811
#define ID_USER_TOOL7                   32812
#define ID_USER_TOOL8                   32813
#define ID_USER_TOOL9                   32814
#define ID_USER_TOOL10                  32815
#define ID_WINDOW_MANAGER               32823
#define ID_FILE_PREFERENCES             32824
#define ID_LEVEL_RESIZELEVEL            32825
#define ID_TOOLS_SEGMENTEDITOR          32826
#define ID_HELP_WEBSITE                 32827
#define ID_HELP_UPDATES                 32828
#define ID_VIEW_ZOOMIN                  32830
#define ID_VIEW                         32833
#define ID_VIEW_VIEW                    32834
#define ID_VIEW_ZOOMOUT                 32835
#define ID_VIEW_INCREASE_SHROUD         32836
#define ID_VIEW_DECREASE_SHROUD         32837
#define ID_VIEW_LAYERS                  32838
#define ID_VIEW_MOVEDOWN_LAYER          32839
#define ID_VIEW_MOVEUP_LAYER            32840
#define ID_VIEW_OVERVIEW                32841
#define ID_VIEW_CLOSEUP                 32842
#define ID_BUTTON32843                  32843
#define ID_MODE_PAINT                   32844
#define ID_MODE_SELECT                  32845
#define ID_MODE_ART                     32846
#define ID_MODE_ENTITY                  32847
#define ID_MODE_WAYPOINT                32848
#define ID_VIEW_MODE                    32849
#define ID_PREFAB_ROTATE                32851
#define ID_PROPERTY_ROTATE              32852
#define ID_PROPERTY_FLIP                32853
#define ID_PROPERTY_MIRROR              32854
#define ID_DRAW_A                       32855
#define ID_DRAW_B                       32856
#define ID_DRAW_C                       32857
#define ID_DRAW_D                       32858
#define ID_STATE_NONE                   32859
#define ID_DRAW_PICK                    32860
#define ID_DRAW_STATE_NONE              32861
#define ID_SELECTION_CUT                32862
#define ID_SELECTION_COPY               32863
#define ID_SELECTION_PASTE              32864
#define ID_SELECTION_REPLACE            32865
#define ID_SELECTION_CLEAR              32866
#define ID_SELECTION_CLEAR_NOPASTE      32867
#define ID_SEGMENT_LINE                 32869
#define ID_SEGMENT_BOX                  32870
#define ID_SEGMENT_CIRCLE               32871
#define ID_SEGMENT_SPRAY                32872
#define ID_SEGMENT_INCREASE             32873
#define ID_SEGMENT_DECREASE             32874
#define ID_ENTITY_DELETE                32875
#define ID_ENTITY_ROTATE_X              32876
#define ID_ENTITY_ROTATE_Y              32877
#define ID_ENTITY_ROTATE_Z              32878
#define ID_WAYPOINT_CREATE              32879
#define ID_VIEW_ROTATE                  32880
#define ID_VIEW_PREFAB                  32881
#define ID_VIEW_SELECTION               32882
#define ID_VIEW_DRAW                    32883
#define ID_VIEW_WAYPOINT                32884
#define ID_VIEW_ROTATE_ENTITY           32885
#define ID_BUTTON_TEST_GAME             32886
#define ID_TEST_GAME                    32887
#define ID_EDIT_UNDO_1                  32889
#define ID_FILE_SAVE_EX                 32890
#define ID_FILE_SAVE_AS_EX              32891
#define ID_EDIT_REDO_1                  32892
#define ID_EDIT_CUT_1                   32893
#define ID_EDIT_COPY_1                  32894
#define ID_EDIT_PASTE_1                 32895
#define ID_WAYPOINT_SELECT              32896
#define ID_TEST_MAP                     32897
#define ID_FILE_BUILDGAME               32898
#define ID_VIEW_TEST_GAME               32900
#define ID_SEGMENTS_PAINTALLOFSEGMENTS  32901
#define ID_SEGMENTS_PAINTONLYWALLS      32902
#define ID_SEGMENTS_PAINTONLYFLOORS     32903
#define ID_SEGMENTS_PICKSEGMENTFROMGRID 32904
#define ID_SEGMENTS_EXTERNALDRAWMODE    32905
#define ID_SEGMENTS_INTERNALDRAWMODE    32906
#define ID_EDITING_SEGMENTMODE          32907
#define ID_EDITING_ENTITYMODE           32908
#define ID_EDITING_CLIPBOARDEDIT        32909
#define ID_EDITING_ZOOMIN               32910
#define ID_EDITING_ZOOMOUT              32911
#define ID_EDITING_MOVEUPALAYER         32912
#define ID_EDITING_MOVEDOWNALAYER       32913
#define ID_EDITING_VIEWENTIRELEVEL      32914
#define ID_ENTITY_VIEW                  32916
#define ID_SEGMENT_VIEW                 32917
#define ID_HELP_CREDITS                 32918
#define ID_APP_CREDITS                  32919
#define ID_FILE_NEWARENA                32920
#define ID_HELP_HELPWIZARD              32922
#define ID_HELP_CHECKFORUPDATES         32923
#define ID_HELP_READMANUAL              32924
#define ID_BUTTON32925                  32925
#define ID_BUTTON32926                  32926
#define ID_BUTTON32927                  32927
#define ID_BUTTON32928                  32928
#define ID__REMOVEITEMFROMCART          32929
#define ID__ADDITEMTOCART               32930
#define ID__ADDITEMTOCART32931          32931
#define ID__APPROVEITEM                 32932
#define ID__DELETEITEM                  32933
#define ID__REMOVEITEM                  32936
#define ID_Menu                         32937
#define ID__RESTOREITEM                 32938
#define ID__EDITITEM                    32939
#define ID__EDITITEM32940               32940
#define ID__EDITITEM32941               32941
#define ID_HELP_TGCSTORE                32942
#define ID_HELP_RESET                   32943
#define ID_HELP_RESET_CHECKS            32944
#define ID_HELP_PLAYINTROAGAIN          32945
#define ID__EDITITEM32946               32946
#define ID__EDITITEM32947               32947
#define ID__EDITITEM32948               32948
#define ID_HELP_CHECKFORUPDATES32949    32949
#define ID__DELETEITEM32950             32950
#define ID_HELP_VIEWITEMLICENSES        32951
#define ID_HELP_WATCHSTOREVIDEO         32952

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        248
#define _APS_NEXT_COMMAND_VALUE         32953
#define _APS_NEXT_CONTROL_VALUE         1258
#define _APS_NEXT_SYMED_VALUE           121
#endif
#endif
